apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: chai-app
  namespace: argocd
  annotations: 
    notifications.argoproj.io/subscribe.on-health-degraded.email: "ashwinsh.91@gmail.com"
    notifications.argoproj.io/subscribe.on-deployed.email: "<receiver@example.com>"
    
spec:
  project: default
  source:
    repoURL: https://github.com/Aswin-Shine/argocdDemo.git
    targetRevision: main
    path: Chai_App

  destination: 
    namespace: argocd
    server: https://172.31.23.114:33893

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

